<?php

namespace Container4nzO1Hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NseKOkKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NseKOkK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NseKOkK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', '.errored.x8DXj3M', NULL, 'Cannot determine controller argument for "App\\Controller\\MainController::perfil()": the $slugger argument is type-hinted with the non-existent class or interface: "App\\Controller\\SluggerInterface". Did you forget to add a use statement?'],
        ], [
            'slugger' => '?',
        ]);
    }
}
