<?php

namespace Container4nzO1Hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRespuestaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RespuestaType' shared autowired service.
     *
     * @return \App\Form\RespuestaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RespuestaType.php';

        return $container->privates['App\\Form\\RespuestaType'] = new \App\Form\RespuestaType();
    }
}
