<?php

namespace Container4nzO1Hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRespuestaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JpCNm0Q.App\Entity\Respuesta' shared service.
     *
     * @return \App\Entity\Respuesta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JpCNm0Q": it references class "App\\Entity\\Respuesta" but no such service exists.');
    }
}
