<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \App\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'texto', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'emisor', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'receptor', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fechaEnvio', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fechaLectura', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'respuestas', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'reportado', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'vehiculo', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'oculto'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'texto', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'emisor', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'receptor', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fechaEnvio', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fechaLectura', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'respuestas', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'reportado', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'vehiculo', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'oculto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', []);

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto(string $texto): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', [$texto]);

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmisor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmisor', []);

        return parent::getEmisor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmisor(int $emisor): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmisor', [$emisor]);

        return parent::setEmisor($emisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceptor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceptor', []);

        return parent::getReceptor();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceptor(int $receptor): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceptor', [$receptor]);

        return parent::setReceptor($receptor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEnvio(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEnvio', []);

        return parent::getFechaEnvio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEnvio(\DateTimeInterface $fechaEnvio): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEnvio', [$fechaEnvio]);

        return parent::setFechaEnvio($fechaEnvio);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaLectura(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaLectura', []);

        return parent::getFechaLectura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaLectura(\DateTimeInterface $fechaLectura): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaLectura', [$fechaLectura]);

        return parent::setFechaLectura($fechaLectura);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getRespuestas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRespuestas', []);

        return parent::getRespuestas();
    }

    /**
     * {@inheritDoc}
     */
    public function addRespuesta(\App\Entity\Respuesta $respuesta): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRespuesta', [$respuesta]);

        return parent::addRespuesta($respuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRespuesta(\App\Entity\Respuesta $respuesta): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRespuesta', [$respuesta]);

        return parent::removeRespuesta($respuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportado', []);

        return parent::getReportado();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportado(bool $reportado): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportado', [$reportado]);

        return parent::setReportado($reportado);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehiculo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehiculo', []);

        return parent::getVehiculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehiculo(int $vehiculo): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehiculo', [$vehiculo]);

        return parent::setVehiculo($vehiculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOculto(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOculto', []);

        return parent::getOculto();
    }

    /**
     * {@inheritDoc}
     */
    public function setOculto(bool $oculto): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOculto', [$oculto]);

        return parent::setOculto($oculto);
    }

}
