<?php

namespace ContainerVyzpTuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CmcOwd6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CmcOwd6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CmcOwd6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'respuestaRepository' => ['privates', 'App\\Repository\\RespuestaRepository', 'getRespuestaRepositoryService', true],
        ], [
            'respuestaRepository' => 'App\\Repository\\RespuestaRepository',
        ]);
    }
}
