<?php

namespace ContainerVyzpTuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZKJew7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gZKJew7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZKJew7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vehiculo' => ['privates', '.errored..service_locator.gZKJew7.App\\Entity\\Vehiculo', NULL, 'Cannot autowire service ".service_locator.gZKJew7": it references class "App\\Entity\\Vehiculo" but no such service exists.'],
        ], [
            'vehiculo' => 'App\\Entity\\Vehiculo',
        ]);
    }
}
