<?php

namespace ContainerA0kJDqh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.N8sf8v1.App\Entity\Message' shared service.
     *
     * @return \App\Entity\Message
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.N8sf8v1": it references class "App\\Entity\\Message" but no such service exists.');
    }
}
