<?php

namespace ContainerA0kJDqh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehiculoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gZKJew7.App\Entity\Vehiculo' shared service.
     *
     * @return \App\Entity\Vehiculo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gZKJew7": it references class "App\\Entity\\Vehiculo" but no such service exists.');
    }
}
