<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyzpTuT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyzpTuT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVyzpTuT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVyzpTuT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVyzpTuT\App_KernelDevDebugContainer([
    'container.build_hash' => 'VyzpTuT',
    'container.build_id' => '7a46455f',
    'container.build_time' => 1621858407,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyzpTuT');
