<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHfGjxg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHfGjxg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHfGjxg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHfGjxg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHfGjxg\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHfGjxg',
    'container.build_id' => 'eb7e3716',
    'container.build_time' => 1619713200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHfGjxg');
