<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGx7oDgd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGx7oDgd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGx7oDgd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGx7oDgd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGx7oDgd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gx7oDgd',
    'container.build_id' => 'a35a10ec',
    'container.build_time' => 1621697152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGx7oDgd');
